# These are supported funding model platforms

github: [naowal,UncleEngineer]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: pypi/uncle-engineer-mooc
custom: # Replace with a single custom sponsorship URL
